package me.blakesmith.soundcloud

import com.fasterxml.jackson.annotation.{JsonProperty, JsonIgnoreProperties}

@JsonIgnoreProperties(ignoreUnknown = true)
class Track (
  @JsonProperty("id") val id: Int,
  @JsonProperty("created_at") val createdAt: String, // Parse the date?
  @JsonProperty("user_id") val userId: Int,
  @JsonProperty("user") val user: MiniUser,
  @JsonProperty("title") val title: String,
  @JsonProperty("permalink") val permalink: String,
  @JsonProperty("permalink_url") val permalinkUrl: String,
  @JsonProperty("uri") val uri: String,
  @JsonProperty("sharing") val sharing: String,
  @JsonProperty("embeddable_by") val embeddableBy: String,
  @JsonProperty("purchase_url") val purchaseUrl: String,
  @JsonProperty("artwork_url") val artworkUrl: String,
  @JsonProperty("description") val description: String,
  @JsonProperty("label") val label: MiniUser,
  @JsonProperty("duration") val duration: Int,
  @JsonProperty("genre") val genre: String,
  @JsonProperty("shared_to_count") val sharedToCount: Int,
  @JsonProperty("tag_list") val tagList: String,
  @JsonProperty("label_id") val labelId: Int,
  @JsonProperty("label_name") val labelName: String,
  @JsonProperty("release") val release: String,
  @JsonProperty("release_day") val releaseDay: Int,
  @JsonProperty("release_month") val releaseMonth: Int,
  @JsonProperty("release_year") val releaseYear: Int,
  @JsonProperty("streamable") val streamable: Boolean,
  @JsonProperty("downloadable") val downloadable: Boolean,
  @JsonProperty("state") val state: String,
  @JsonProperty("license") val license: String,
  @JsonProperty("track_type") val trackType: String,
  @JsonProperty("waveform_url") val waveformUrl: String,
  @JsonProperty("download_url") val downloadUrl: String,
  @JsonProperty("stream_url") val streamUrl: String,
  @JsonProperty("video_url") val videoUrl: String,
  @JsonProperty("bpm") val bpm: Int,
  @JsonProperty("commentable") val commentable: Boolean,
  @JsonProperty("isrc") val isrc: String,
  @JsonProperty("key_signature") val keySignature: String,
  @JsonProperty("comment_count") val commentCount: String,
  @JsonProperty("download_count") val downloadCount: String,
  @JsonProperty("playback_count") val playbackCount: String,
  @JsonProperty("favoritings_count") val favoritingsCount: Int,
  @JsonProperty("original_format") val originalFormat: String,
  @JsonProperty("original_content_size") val originalContentSize: Int,
  @JsonProperty("created_with") val createdWith: App,
  @JsonProperty("asset_data") val assetData: Array[Byte],
  @JsonProperty("artwork_data") val artworkData: Array[Byte],
  @JsonProperty("user_favorite") val userFavorite: Boolean
)
